<a href="https://colab.research.google.com/github/Progr4m4573R/MSc-Robotics-and-Autonomous-Systems/blob/main/Advanced%20Artificial%20Intelligence/AAI%20Assignment%201/AAI%20Assignment%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assuming X ∈ {nothing, placebo, medicine} is the possible treatment, Y ∈ {survive, ¬survive} is 
the outcome, and Z ∈ {healthy, ¬healthy} is the mental condition:
a) 

Represent the above situation with a Causal Bayesian Network (CBN) and its conditional 
probability tables (CPTs)

P(X,Y,Z) Can be decomposed into:

P(Y|X,Z)
P(X|Z)
P(Z)

In [58]:
import pandas as pd
import numpy as np
df = pd.read_csv('assignment1_dataset.csv')
print(df)

     Z  X  Y
0    1  2  1
1    0  2  1
2    1  2  1
3    1  0  1
4    1  1  1
..  .. .. ..
995  1  2  1
996  1  2  1
997  1  2  1
998  1  0  1
999  1  0  1

[1000 rows x 3 columns]


In the dataset, assume the following meanings:

X=0 --> nothing

X=1 --> placebo

X=2 --> medicine

Y=0 --> ¬survive

Y=1 --> survive

Z=0 --> ¬healthy

Z=1 --> healthy

![CBN diagram](CBN_image.png "Title")

In [59]:
#https://www.marsja.se/pandas-count-occurrences-in-column-unique-values/
Y = (df['Y']).value_counts(normalize=True)
X = (df['X']).value_counts(normalize=True)
Z = (df['Z']).value_counts(normalize=True)
t, f = 1, 0
print("survive or not\n",Y,"\nMedicine or not\n",X,"\nHealthy or not \n",Z)

survive or not
 1    0.746
0    0.254
Name: Y, dtype: float64 
Medicine or not
 1    0.436
2    0.393
0    0.171
Name: X, dtype: float64 
Healthy or not 
 1    0.728
0    0.272
Name: Z, dtype: float64


In [92]:
#P(X/Z)
x_0andz_0 =     df[(df['X']==0)&(df['Z']==0)]
x_0andz_1 =     df[(df['X']==0)&(df['Z']==1)]
not_x_0andz_0 = df[(df['X']!=0)&(df['Z']==0)]
not_x_0andz_1 = df[(df['X']!=0)&(df['Z']==1)]

x_1andz_0 =     df[(df['X']==1)&(df['Z']==0)]
x_1andz_1 =     df[(df['X']==1)&(df['Z']==1)]
not_x_1andz_0 = df[(df['X']!=1)&(df['Z']==0)]
not_x_1andz_1 = df[(df['X']!=1)&(df['Z']==1)]

x_2andz_0 =     df[(df['X']==2)&(df['Z']==0)]
x_2andz_1 =     df[(df['X']==2)&(df['Z']==1)]
not_x_2andz_0 = df[(df['X']!=2)&(df['Z']==0)]
not_x_2andz_1 = df[(df['X']!=2)&(df['Z']==1)]

#P(Y,X/Z)
y_x0_z0 = df[(df['Y']==1)&(df['X']==0)&(df['Z']==0)]
y_x0_z1 = df[(df['Y']==1)&(df['X']==0)&(df['Z']==1)]
y_not_x0_z0 = df[(df['Y']==1)&(df['X']!=0)&(df['Z']==0)]
y_not_x0_z1 = df[(df['Y']==1)&(df['X']!=0)&(df['Z']==1)]

y_x1_z0 = df[(df['Y']==1)&(df['X']==1)&(df['Z']==0)]
y_x1_z1 = df[(df['Y']==1)&(df['X']==1)&(df['Z']==1)]
y_not_x1_z0 = df[(df['Y']==1)&(df['X']!=1)&(df['Z']==0)]
y_not_x1_z1 = df[(df['Y']==1)&(df['X']!=1)&(df['Z']==1)]

y_x2_z0 = df[(df['Y']==1)&(df['X']==2)&(df['Z']==0)]
y_x2_z1 = df[(df['Y']==1)&(df['X']==2)&(df['Z']==1)]
y_not_x2_z0 = df[(df['Y']==1)&(df['X']!=2)&(df['Z']==0)]
y_not_x2_z1 = df[(df['Y']==1)&(df['X']!=2)&(df['Z']==1)]



#P(x0/X|Z)
#x is 0 and z is 0, WHEN X = nothing and patient not healthy 
P_of_x0_given_z0 = (len(x_0andz_0.index)/Z[f])*(1/1000)
#When X is not 0 and Z is 1, when X =  treatment and patient healthy
P_of_not_x0_given_z1 = (len(not_x_0andz_1.index)/Z[t])*(1/1000)

#When x is not 0 and z is 0, WHEN X = treatment and patient not healthy
P_of_not_x0_given_z0 = (len(not_x_0andz_0.index)/Z[f])*(1/1000)
#When X is 0 and Z is 1, when X = no treatment and patient healthy
P_of_x0_given_z1 = (len(x_0andz_1.index)/Z[t])*(1/1000)

#P(x1/X|Z)--PLACEBO
#WHEN X = 1 and patient healthy
P_of_x1_given_z1 = (len(x_1andz_1.index)/Z[t])*(1/1000)
P_of_not_x1_given_z1 = (len(not_x_1andz_1.index)/Z[t])*(1/1000)
#WHEN X = 1 and patient not healthy
P_of_x1_given_z0 = (len(x_1andz_0.index)/Z[f])*(1/1000)
P_of_not_x1_given_z0 = (len(not_x_1andz_0.index)/Z[f])*(1/1000)
                        
#P(x2/X|Z)--MEDICINE
#When x is true and z is false, WHEN X = 2 and patient not healthy
P_of_x2_given_z1 = (len(x_2andz_1.index)/Z[t])*(1/1000)
P_of_not_x2_given_z1 = (len(not_x_2andz_1.index)/Z[t])*(1/1000)                        
#When x is false and z is false, When x = 1 or 0 and patient not healthy
P_of_x2_given_z0 = (len(x_2andz_0.index)/Z[f])*(1/1000)
P_of_not_x2_given_z0 = (len(not_x_2andz_0.index)/Z[f])*(1/1000)
                        
#P(Y/X,Z)
Y_GIVEN_P_X0_Z0 = (len(y_x0_z0.index)/P_of_x0_given_z0)*(1/1000)
Y_GIVEN_P_X0_Z1 = (len(y_x0_z1.index)/P_of_x0_given_z1)*(1/1000)
Y_GIVEN_P_not_X0_Z0 = (len(y_not_x0_z0.index)/P_of_not_x0_given_z0)*(1/1000)
Y_GIVEN_P_not_X0_Z1 =  (len(y_not_x0_z1.index)/P_of_not_x0_given_z1)*(1/1000)

Y_GIVEN_P_X1_Z0 = (len(y_x1_z0.index)/P_of_x1_given_z0)*(1/1000)
Y_GIVEN_P_X1_Z1 = (len(y_x1_z1.index)/P_of_x1_given_z1)*(1/1000)
Y_GIVEN_P_not_X1_Z0 = (len(y_not_x1_z0.index)/P_of_not_x1_given_z0)*(1/1000)
Y_GIVEN_P_not_X1_Z1 = (len(y_not_x1_z1.index)/P_of_not_x1_given_z1)*(1/1000)

Y_GIVEN_P_X2_Z0 = (len(y_x2_z0.index)/P_of_x2_given_z0)*(1/1000)
Y_GIVEN_P_X2_Z1 = (len(y_x2_z1.index)/P_of_x2_given_z1)*(1/1000)    
Y_GIVEN_P_not_X2_Z0 = (len(y_not_x2_z0.index)/P_of_not_x2_given_z0)*(1/1000)
Y_GIVEN_P_not_X2_Z1 = (len(y_not_x2_z1.index)/P_of_not_x2_given_z1)*(1/1000) 


#Treatment and not healthy
#print("Treatment and not healthy", P_of_not_x0_given_z0)
#No treatment and not healthy
print("No treatment and not healthy", P_of_x0_given_z0)

#Treatment and healthy
#print("Treatment and healthy", P_of_not_x0_given_z1)
#No treatment and healthy
print("No treatment and healthy", P_of_x0_given_z1)

#Medicine and not healthy
print("\nMedicine and not healthy", P_of_x2_given_z0)
#No Medicine and healthy
print("Medicine and healthy", P_of_x2_given_z1)

#Placebo and not healthy
print("\nPlacebo and not healthy", P_of_x1_given_z0)
#No Placebo and healthy
print("Placebo and healthy", P_of_x1_given_z1)


No treatment and not healthy 0.09926470588235294
No treatment and healthy 0.19780219780219782

Medicine and not healthy 0.4779411764705882
Medicine and healthy 0.3612637362637363

Placebo and not healthy 0.42279411764705876
Placebo and healthy 0.4409340659340659


AttributeError: 'DataFrame' object has no attribute 'values_counts'

In [61]:
p_x0_z1 = np.array([1-P_of_x0_given_z1, P_of_x0_given_z1])
P_x0_z0 = np.array([1-P_of_x0_given_z0, P_of_x0_given_z0])

p_x1_z1 = np.array([1-P_of_x1_given_z1, P_of_x1_given_z1])
p_x1_z0 = np.array([1-P_of_x1_given_z0, P_of_x1_given_z0])

p_x2_z1 = np.array([1-P_of_x2_given_z1, P_of_x2_given_z1])
p_x2_z0 = np.array([1-P_of_x2_given_z0, P_of_x2_given_z0])

p_y_x0_z1 = np.array([1-Y_GIVEN_P_X0_Z1, Y_GIVEN_P_X0_Z1])
p_y_x0_z0 = np.array([1-Y_GIVEN_P_X0_Z0, Y_GIVEN_P_X0_Z0])

p_y_x1_z1 = np.array([1-Y_GIVEN_P_X1_Z1, Y_GIVEN_P_X1_Z1])
p_y_x1_z0 = np.array([1-Y_GIVEN_P_X1_Z0, Y_GIVEN_P_X1_Z0])

p_y_x2_z1 = np.array([1-Y_GIVEN_P_X2_Z1, Y_GIVEN_P_X2_Z1])
p_y_x2_z0 = np.array([1-Y_GIVEN_P_X2_Z0, Y_GIVEN_P_X2_Z0])


 Implement and document a Python program that reads the given dataset and automatically 
computes the intervention’s probability P(Y | do(X)) for all the possible values of X and Y. [40 
points]

In [22]:
def y_do_x(y_x_z, y_x_not_z, y_not_x_z,y_not_x_not_z,z):
    y1_x1 = (y_x_z * z[t]) + (y_x_not_z * z[f])
    
    y1_x0 = (y_not_x_z * z[t]) + (y_not_x_not_z * z[f])
    
    return y1_x1, y1_x0
    #Computes Y TRUE/FALSE given Z is TRUE 
    #AND Y TRUE/FALSE Given Z is false

In [23]:
y_do_x(p_y_x0_z1,p_y_x0_z0,p_y_x1_z1,p_y_x1_z0,Z)

(array([0.53744652, 0.46255348]), array([0.55826679, 0.44173321]))

In [11]:
y_do_x(p_y_x1_z1,p_y_x1_z0,p_y_x0_z1,p_y_x0_z0,Z)

(array([0.55826679, 0.44173321]), array([0.53744652, 0.46255348]))

In [12]:
y_do_x(p_y_x2_z1,p_y_x2_z0,p_y_x2_z1,p_y_x2_z0,Z)

(array([0.47740381, 0.52259619]), array([0.47740381, 0.52259619]))

Modify the CBN to introduce another variable W ∈ {gene, ¬gene}, which indicates whether 
the patient is genetically predisposed to some mental problem. This influences the actual 
mental condition Z according to the following probabilities: 
P(Z = healthy | W = gene) = 0.6 
P(Z = healthy | W = ¬gene) = 0.8 
P(W = gene) = 0.1 
Implement and document a Python program for the new CBN that computes the average 
causal effect (ACE) of the genetic profile W on the patient’s survival Y.  [40 points]

![CBN diagram](CBN_image_part_c.png "Title")

In [95]:
P_Z_W = np.array([[0.6,0.4],[0.8,0.2]])
P_W = np.array([0.1,0.9])
#P(Y,X,Z,W)
#P(Y,X,Z)*(X/Z)*(Z/W)*(W)
#Intervene on X
# P(Y|do(w), = P(y/w)
#P(Y=1,X=1,Z=1)*(Z=1,W=1)*(W=1) + P(Y=1,X=1,Z=0)*(Z=0,W=0)*(W=0) +  
#P(Y=1,X=0,Z=1)*(Z=1,W=1)*(W=1) + P(Y=1,X=0,Z=0)*(Z=0,W=0)*(W=0)

P(Y|w)=αP(Y,w)

=α  ∑z,x P(Y,x,w,z)

=α  ∑z∑xP(Y|x,z) * P(x|z) * P(z|w) * P(w)

=α  P(x|z) * ∑zP(z|w) * ∑xP(Y|x,z) * P(w)

𝐏(Y|W)=⟨--(𝑃(y|w),𝑃(¬y|w)--) + (--𝑃(y|¬w),𝑃(¬y|¬w)--)⟩:

In [106]:
#Y|do(x),W
def Y_W(y_x_z, y_not_x_z, y_x_not_z, x_z,x_not_z,z_w,w):
    y1_w1 = w[t]*(z_w[t,t]*(y_x_z[t] *x_z[t] + y_not_x_z*x_z[f]) + z_w[f,t]*((y_x_not_z[t] *x_not_z[t] + y_x_z[t] *x_not_z[f])))
    
    y1_w0 = w[f]*(z_w[t,f]*(y_x_z[t] *x_z[t] + y_not_x_z*x_z[f]) + z_w[f,f]*((y_x_not_z[t] *x_not_z[t] + y_x_z[t] *x_not_z[f])))
    
    
    return y1_w1 - y1_w0

In [115]:
sum1 = Y_W(p_y_x1_z1,
           P_of_not_x1_given_z1,
           p_y_x1_z0,
           p_x1_z1,
           p_x1_z0,
           P_Z_W,
           P_W)#y/x1
sum2 = Y_W(p_y_x0_z1,
           P_of_not_x0_given_z1,
           p_y_x0_z0,
           p_x0_z1,
           P_x0_z0,
           P_Z_W,
           P_W)#y/x0 
sum3 = Y_W(p_y_x2_z1,
           P_of_not_x2_given_z1,
           p_y_x2_z0,
           p_x2_z1,
           p_x2_z0,
           P_Z_W,
           P_W)#y/x2

Output = sum1+sum2+sum3
Output

0.5981182963400979

sum1 = ACE(p_y_x1_z1,
           p_y_x1_z1,
           p_y_x0_z1,
           p_y_x1_z0,
           P_Z_W,P_W)#y/x1
sum1

In [53]:
#Experimenting

#X = 0 OR NOT
#x_0andz_0.value_counts()
#y_given_x0_and_z1 = x_0andz_1.value_counts()
#not_x_0andz_0.value_counts()
#not_x_0andz_1.value_counts()

#X = 1 OR NOT
#x_1andz_0.value_counts()
#x_1andz_1.value_counts()
#not_x_1andz_0.value_counts()
#not_x_1andz_1.value_counts()

#X = 2 OR NOT
#x_2andz_0.value_counts()

#x_2andz_1.value_counts()
#not_x_2andz_0.value_counts()
#not_x_2andz_1.value_counts()

AttributeError: 'DataFrame' object has no attribute 'value_counts'